project:
  type: website
  output-dir: _output

# website
website:
  # basics
  title: "NetSky AI"
  site-url: https://netsky.ai
  repo-url: https://github.com/netsky-ai/website
  description: "AI enabling every employee, not just developers."
  favicon: logo.png

  # options
  reader-mode: false
  back-to-top-navigation: true
  open-graph:
    image: logo.png
  twitter-card:
    image: logo.png


  # search
  search:
    location: navbar
    type: overlay

  # navbar
  navbar:
    background: "#c77218"
    left:
      - text: "about"
        href: about.qmd
    right:
      - text: "blog"
        href: posts.qmd

  # footer
  page-footer:
    border: false
    center: "NetSky AI"
    right:
      - icon: github
        href: https://github.com/netsky-ai

# theme
format:
  html:
    theme: solar
    toc: true
