project:
  type: website
  output-dir: _output

# website
website:
  # basics
  title: "NetSky"
  site-url: https://netsky.ai
  repo-url: https://github.com/netsky-ai/website
  description: "AI enabling every employee, not just developers."
  favicon: logo.png

  # options
  reader-mode: false
  back-to-top-navigation: true
  open-graph:
    image: logo.png
  twitter-card:
    image: logo.png


  # search
  search:
    location: navbar
    type: overlay

  # navbar
  navbar:
    logo: logo.png
    background: "#f17f16"
    left:
      - text: "Demo"
        href: demo.qmd
      - text: "Services"
        href: services.qmd
    right:
      - text: "About"
        href: about.qmd
      - text: "Blog"
        href: posts.qmd

  # footer
  page-footer:
    border: false
    center: "NetSky"
    right:
      - icon: github
        href: https://github.com/netsky-ai

# theme
format:
  html:
    theme: superhero
    toc: true
